### ISSUE TITLE
testbench for emmu is out of sync with RTL

### ISSUE THREAD

**Issue by olofk** [parallella/parallella-hw#12]
The interface of emmu.v seems to have been changed since dv_emmu was written. I tried to do some simple renaming, but there seem to be more changes needed

**Comment by aolofsson** [comment]
Should be fixed now, need to put back dual ported memory model to verify but it compiles again.

**Comment by olofk** [comment]
Confirmed. Even though the test itself isn't overly comprehensive, the code compiles and runs with both icarus and modelsim. I've updated the .core file in my repo, so the test can be run with fusesoc sim --force emmu

**Comment by olofk** [comment]
I did some more quick and dirty hacking and the testbench runs under verilator now as well.

**Comment by aolofsson** [comment]
Looks good! Can you submit as a PR?
