### ISSUE TITLE
corrupted clock settings

### ISSUE THREAD

**Issue by shodruky-rhyammer** [parallella/parallella-hw#8]
In parallella_7020_hdmi:
XPS > Clock Generation > PL Fabric Clocks > FCLK_CLK1 is set to 152.
I changed it to 125.

In parallella_7010_hdmi, parallella_7020_hdmi:
XPS > Bus Interfaces > clock_generator_0 > (right click) > Configure IP > CLKIN: Input Clock Frequency: 0 (changed to 100000000)

CLKOUT0: Required Frequency: 0 (changed to 12288135)

**Comment by aolofsson** [comment]
depracated
